version: '3.9'

services:
  client:
    container_name: praktikum-client
    image: praktikum-client
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        CLIENT_PORT: ${CLIENT_PORT}
    restart: always
    ports:
      - '${CLIENT_PORT}:80'
    env_file:
      - .env
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      - server
    networks:
      - skynet

  server:
    container_name: praktikum-server
    image: praktikum-server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      SERVER_PORT: ${SERVER_PORT}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - skynet

  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:14
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - skynet

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - '${PGADMIN_PORT}:80'
    env_file:
      - .env
    environment:
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 0
    volumes:
    # to fix permission bugs:
    # sudo chown -R 5050:5050 ./tmp/pgadmin
      - ./tmp/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - skynet

networks:
  skynet:
    driver: bridge
